DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(20) DEFAULT "",
  `pass` VARCHAR(200) DEFAULT "",
  `gm_modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gm_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`name`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;