DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `pass` VARCHAR(200) NOT NULL,
  `identity` VARCHAR(20) NOT NULL,
  `gm_modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gm_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`name`),
  UNIQUE KEY (`identity`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `apps`;
CREATE TABLE `apps`(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `owner` INT UNSIGNED NOT NULL,
  `secret` VARCHAR(50) NOT NULL,
  `gm_modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gm_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`owner`, `name`),
  INDEX (`owner`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `members`;
CREATE TABLE `members`(
  `id` INT UNSIGNED AUTO_INCREMENT,
  `app` INT UNSIGNED NOT NULL,
  `user` INT UNSIGNED NOT NULL,
  `status` INT UNSIGNED NOT NULL COMMENT '1: inviting, 2: joined',
  `gm_modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gm_create` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`app`, `user`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;